CREATE TABLE IF NOT EXISTS TB_USER(
	USER_SEQ INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(100) NOT NULL,
    USER_PASSWORD VARCHAR(100) NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    USER_PHONE_NUMBER INT(12) NOT NULL
);

SELECT * FROM TB_USER;

INSERT INTO TB_USER
(USER_ID, USER_PASSWORD, USER_NAME, USER_PHONE_NUMBER)
VALUES
("first_id", "1234", "HongGilDong", 01010101010),
("second_id", "1234", "HongGilDong2", 01020102010);

SELECT * FROM TB_USER;

-- DROP TABLE TB_USER; 